[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{% if commit.breaking %}**BREAKING:** {% endif %}{{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](<REPO>/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}
"""
trim = true
render_always = true
postprocessors = [
  { pattern = "<REPO>", replace = "https://github.com/perplexityai/codescythe" },
]

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
protect_breaking_commits = true
filter_commits = false
tag_pattern = "codescythe_cli_v[0-9]*"
sort_commits = "oldest"
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^docs", group = "Documentation" },
  { message = "^refactor", group = "Refactor" },
  { message = "^test", group = "Tests" },
  { message = "^build", group = "Build" },
  { message = "^ci", group = "CI" },
  { message = "^revert", group = "Reverts" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore", group = "Chores" },
  { message = ".*", group = "Other" },
]
