name: test functional

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  functional_test:
    name: Functional tests
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-functional-test
          repository-cache: true

      - name: Test functional targets
        run: bazel test //... --build_tests_only --test_tag_filters=functional_test
