name: test functional

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  functional_test:
    name: Functional tests
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-functional-test
          repository-cache: true

      - name: Test functional targets
        run: bazel test //... --build_tests_only --test_tag_filters=functional_test
