name: test native

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Rust
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-test
          repository-cache: true

      - name: Test
        run: bazel test //... --build_tests_only --test_tag_filters=-functional_test
